name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          repository: champierre/ml2scratch
          path: ./ml2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/posenet2scratch
          path: ./posenet2scratch
      - uses: actions/checkout@v2
        with:
          repository: yokobond/scratch-vm
          ref: extension/microbit-more
          path: ./microbit-more-scratch-vm
      - uses: actions/checkout@v2
        with:
          repository: yokobond/scratch-ext
          ref: microbit-more
          path: ./microbit-more-scratch-ext
      - uses: actions/checkout@v2
        with:
          repository: champierre/tm2scratch
          path: ./tm2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/scratch2maqueen
          path: ./scratch2maqueen
      - uses: actions/checkout@v2
        with:
          repository: champierre/handpose2scratch
          path: ./handpose2scratch
      - run: sh ./handpose2scratch/install.sh          
      - run: sh ./scratch2maqueen/install_for_github_actions.sh
      - run: sh ./tm2scratch/install_for_github_actions.sh
      - run: sh ./tm2scratch/install_microbit_more_for_github_actions.sh
      - run: sh ./posenet2scratch/install_for_github_actions.sh
      - run: sh ./ml2scratch/install_for_github_actions.sh
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
